version: '3'

services:
 web:
  build: .
  ports:
   - "9015:80"
  volumes:
   - ./www:/var/www/html

 db:
  image: mysql:5.7
  environment:
   MYSQL_ROOT_PASSWORD: secret

 phpmyadmin:
  image: phpmyadmin/phpmyadmin
  environment: 
   MYSQL_ROOT_PASSWORD: secret
  ports:
   - "8085:80"
